export const allListings = [
  {
    seller: "CollectorsCoveTcg",
    condition: "Lightly Played Holofoil",
    price: "$45.00",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Miracle Terminus",
    condition: "Lightly Played Holofoil",
    price: "$49.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GameStoreanMore",
    condition: "Lightly Played Holofoil",
    price: "$51.95",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SingleSlayer",
    condition: "Lightly Played Holofoil",
    price: "$52.54",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Deck Factory Gaming",
    condition: "Lightly Played Holofoil",
    price: "$53.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "LI Collectables",
    condition: "Near Mint Holofoil",
    price: "$53.01",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Meteorite Industries",
    condition: "Near Mint Holofoil",
    price: "$53.01",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Cyber Cards TCG",
    condition: "Near Mint Holofoil",
    price: "$52.78",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "CollectorsCoveTcg",
    condition: "Near Mint Holofoil",
    price: "$52.78",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Blue Black Control",
    condition: "Near Mint Holofoil",
    price: "$54.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TCGPackPulls",
    condition: "Near Mint Holofoil",
    price: "$54.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "OHKO Games",
    condition: "Near Mint Holofoil",
    price: "$54.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SellingTradingCards",
    condition: "Lightly Played Holofoil",
    price: "$54.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Cardboard Castle CA",
    condition: "Lightly Played Holofoil",
    price: "$51.89",
    shipping: "+ $3.00 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Ratchets&Wrenches",
    condition: "Near Mint Holofoil",
    price: "$50.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Cardboard For Life",
    condition: "Near Mint Holofoil",
    price: "$54.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Space Coast Games",
    condition: "Near Mint Holofoil",
    price: "$54.00",
    shipping: "+ $1.29 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ThreeFriends",
    condition: "Lightly Played Holofoil",
    price: "$53.72",
    shipping: "+ $1.69 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ThePokeHive",
    condition: "Near Mint Holofoil",
    price: "$54.43",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TheGreatestTCG",
    condition: "Near Mint Holofoil",
    price: "$55.68",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Tap N Roll",
    condition: "Lightly Played Holofoil",
    price: "$51.88",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeCardClub",
    condition: "Near Mint Holofoil",
    price: "$55.93",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Veterans pokefarm",
    condition: "Near Mint Holofoil",
    price: "$53.97",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ShazbatCards",
    condition: "Lightly Played Holofoil",
    price: "$54.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Gamers Headquarters",
    condition: "Near Mint Holofoil",
    price: "$53.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Alternate Dimensions",
    condition: "Lightly Played Holofoil",
    price: "$54.00",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Scrub Tier Gaming",
    condition: "Near Mint Holofoil",
    price: "$56.30",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Luxury Gaming TCG",
    condition: "Near Mint Holofoil",
    price: "$55.00",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Galactic GrandHaven",
    condition: "Lightly Played Holofoil",
    price: "$51.88",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Galaxy Games LLC",
    condition: "Lightly Played Holofoil",
    price: "$54.89",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GameStoreanMore",
    condition: "Near Mint Holofoil",
    price: "$56.95",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TheGarShop",
    condition: "Near Mint Holofoil",
    price: "$56.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Magic City Poke",
    condition: "Near Mint Holofoil",
    price: "$56.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeVarsity",
    condition: "Lightly Played Holofoil",
    price: "$55.00",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "OneNDunn Cards",
    condition: "Lightly Played Holofoil",
    price: "$57.07",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "DesertCollects",
    condition: "Near Mint Holofoil",
    price: "$55.91",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeBash TCG",
    condition: "Lightly Played Holofoil",
    price: "$57.45",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeyTrapKing TCG",
    condition: "Near Mint Holofoil",
    price: "$56.74",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Pokebearguy",
    condition: "Near Mint Holofoil",
    price: "$53.99",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Evolved Collectors",
    condition: "Near Mint Holofoil",
    price: "$57.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Progress CCG",
    condition: "Near Mint Holofoil",
    price: "$54.10",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Atlantis Cards",
    condition: "Near Mint Holofoil",
    price: "$57.21",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Paper Tiger Co",
    condition: "Near Mint Holofoil",
    price: "$56.26",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GemMint Beaubasaur",
    condition: "Near Mint Holofoil",
    price: "$57.00",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "FirstLightTCG",
    condition: "Near Mint Holofoil",
    price: "$58.31",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Kamironin Cards",
    condition: "Near Mint Holofoil",
    price: "$57.05",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Jimanthas Cardshop",
    condition: "Near Mint Holofoil",
    price: "$57.00",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Full Art TCG",
    condition: "Near Mint Holofoil",
    price: "$56.55",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ProjectCCG",
    condition: "Near Mint Holofoil",
    price: "$58.60",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Downtime Gaming",
    condition: "Near Mint Holofoil",
    price: "$58.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Downtime Gaming",
    condition: "Near Mint Holofoil",
    price: "$58.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Champion City Hobby",
    condition: "Near Mint Holofoil",
    price: "$58.29",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Express TCG",
    condition: "Near Mint Holofoil",
    price: "$59.41",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GingerbreadJune",
    condition: "Near Mint Holofoil",
    price: "$58.36",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Super Nova Toys",
    condition: "Lightly Played Holofoil",
    price: "$57.69",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeQueenDr",
    condition: "Lightly Played Holofoil",
    price: "$54.84",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MegsPokeHunt",
    condition: "Near Mint Holofoil",
    price: "$55.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Health Points TCG",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "BulkemonStore",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "American Deals",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ROC Games LLC",
    condition: "Near Mint Holofoil",
    price: "$59.39",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Station seventy six",
    condition: "Lightly Played Holofoil",
    price: "$59.00",
    shipping: "+ $1.76 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PikamewVStar",
    condition: "Near Mint Holofoil",
    price: "$59.34",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "humbled gaming",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "EclipseCardsandHobby",
    condition: "Near Mint Holofoil",
    price: "$58.97",
    shipping: "+ $2.19 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "OneUpTCG Tuscaloosa",
    condition: "Near Mint Holofoil",
    price: "$61.24",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MDM Cards",
    condition: "Near Mint Holofoil",
    price: "$58.00",
    shipping: "+ $3.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Super Nova Toys",
    condition: "Near Mint Holofoil",
    price: "$59.71",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "lancewillsellit",
    condition: "Lightly Played Holofoil",
    price: "$61.74",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Symphony Games",
    condition: "Lightly Played Holofoil",
    price: "$61.21",
    shipping: "+ $0.78 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "CharizardStoressss",
    condition: "Near Mint Holofoil",
    price: "$57.17",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Owl Central Games",
    condition: "Near Mint Holofoil",
    price: "$62.47",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "okiebreakbros",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Hendrix TCG Shop",
    condition: "Near Mint Holofoil",
    price: "$58.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeStopMotion",
    condition: "Near Mint Holofoil",
    price: "$58.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TCG FUNatics",
    condition: "Near Mint Holofoil",
    price: "$63.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "tcg foster",
    condition: "Near Mint Holofoil",
    price: "$61.96",
    shipping: "+ $1.11 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Early MN TCG",
    condition: "Near Mint Holofoil",
    price: "$62.00",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "mabtcg",
    condition: "Near Mint Holofoil",
    price: "$62.36",
    shipping: "+ $1.15 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Untapped Games",
    condition: "Near Mint Holofoil",
    price: "$62.08",
    shipping: "+ $1.44 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TalkNerdyToMe",
    condition: "Near Mint Holofoil",
    price: "$58.95",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Game Nut",
    condition: "Lightly Played Holofoil",
    price: "$59.99",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "CollectersDream",
    condition: "Near Mint Holofoil",
    price: "$59.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PhantasmGaming",
    condition: "Near Mint Holofoil",
    price: "$64.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Card Guys Jasper",
    condition: "Near Mint Holofoil",
    price: "$62.99",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokEliteCardz",
    condition: "Near Mint Holofoil",
    price: "$59.34",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "KalEls Kards",
    condition: "Moderately Played Holofoil",
    price: "$62.99",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Amazing Discoveries",
    condition: "Lightly Played Holofoil",
    price: "$64.68",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Sullys Abode",
    condition: "Near Mint Holofoil",
    price: "$64.80",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "AlwaysMintCardsBySky",
    condition: "Near Mint Holofoil",
    price: "$59.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Skrtcurts",
    condition: "Near Mint Holofoil",
    price: "$60.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "OliverShops",
    condition: "Near Mint Holofoil",
    price: "$65.20",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PrimapesCards",
    condition: "Near Mint Holofoil",
    price: "$64.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "AMB Trading Cards",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The Jones TCG",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TheMaynEvent TCG",
    condition: "Near Mint Holofoil",
    price: "$65.05",
    shipping: "+ $1.42 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MegaGarchomp",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The PokeBar",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $1.69 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Nerd Rage Gaming",
    condition: "Near Mint Holofoil",
    price: "$66.75",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "AAA Collectibles",
    condition: "Near Mint Holofoil",
    price: "$66.78",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Casters Collectibles",
    condition: "Near Mint Holofoil",
    price: "$62.25",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "StrikeZoneOnline",
    condition: "Near Mint Holofoil",
    price: "$64.99",
    shipping: "+ $2.49 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Klutzee TCG",
    condition: "Near Mint Holofoil",
    price: "$62.49",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "zdfiiiiii",
    condition: "Near Mint Holofoil",
    price: "$66.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Littleroot Games",
    condition: "Lightly Played Holofoil",
    price: "$68.11",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MatrixCardsLLC",
    condition: "Near Mint Holofoil",
    price: "$68.24",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "DayDreamGames",
    condition: "Near Mint Holofoil",
    price: "$68.79",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Masenko Cards",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $4.25 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "NetzzJD",
    condition: "Near Mint Holofoil",
    price: "$64.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Mint Treasures TCG",
    condition: "Near Mint Holofoil",
    price: "$69.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Scotty PokeStop",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "AnochronisticCowboy",
    condition: "Near Mint Holofoil",
    price: "$65.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SpaceCatCollectibles",
    condition: "Near Mint Holofoil",
    price: "$68.00",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "WannaSmash",
    condition: "Lightly Played Holofoil",
    price: "$70.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Bandit Goods",
    condition: "Near Mint Holofoil",
    price: "$70.22",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "HotsauceGames",
    condition: "Near Mint Holofoil",
    price: "$70.24",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MamiVonsCardShop",
    condition: "Near Mint Holofoil",
    price: "$65.95",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Red Heart",
    condition: "Near Mint Holofoil",
    price: "$69.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ShadowGamesTCG",
    condition: "Near Mint Holofoil",
    price: "$69.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "LoSo Poke Shop",
    condition: "Near Mint Holofoil",
    price: "$69.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Finch and Sparrow",
    condition: "Near Mint Holofoil",
    price: "$71.22",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Alberick",
    condition: "Near Mint Holofoil",
    price: "$71.25",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "DiscountGamesInc",
    condition: "Near Mint Holofoil",
    price: "$71.33",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Play to Win Games",
    condition: "Lightly Played Holofoil",
    price: "$71.98",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Braven Plays",
    condition: "Near Mint Holofoil",
    price: "$70.91",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "EM Cards PEI",
    condition: "Moderately Played Holofoil",
    price: "$67.96",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "DynamicCardCollector",
    condition: "Near Mint Holofoil",
    price: "$73.20",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "DariosCards",
    condition: "Near Mint Holofoil",
    price: "$72.00",
    shipping: "+ $1.58 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ModernEraCollections",
    condition: "Near Mint Holofoil",
    price: "$69.95",
    shipping: "+ $3.95 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Game Nut",
    condition: "Near Mint Holofoil",
    price: "$69.99",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Alfa Shop",
    condition: "Near Mint Holofoil",
    price: "$70.00",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeRon PokeRon",
    condition: "Near Mint Holofoil",
    price: "$69.70",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ParadoxTradingPost",
    condition: "Moderately Played Holofoil",
    price: "$74.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Forty Two TCG",
    condition: "Moderately Played Holofoil",
    price: "$74.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SaltySwanShop",
    condition: "Near Mint Holofoil",
    price: "$70.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Stonedrink Collects",
    condition: "Near Mint Holofoil",
    price: "$75.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Geeked Out Garage",
    condition: "Near Mint Holofoil",
    price: "$75.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "NandJ",
    condition: "Near Mint Holofoil",
    price: "$75.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Games and Cards",
    condition: "Near Mint Holofoil",
    price: "$73.70",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Play Unplugged",
    condition: "Near Mint Holofoil",
    price: "$70.21",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Dash Collectibles",
    condition: "Near Mint Holofoil",
    price: "$75.78",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Troll Acquisitions",
    condition: "Near Mint Holofoil",
    price: "$76.95",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Incognito Shop",
    condition: "Near Mint Holofoil",
    price: "$75.00",
    shipping: "+ $2.00 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Mythic Deck",
    condition: "Near Mint Holofoil",
    price: "$75.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "EliteCollectorTCG",
    condition: "Near Mint Holofoil",
    price: "$75.00",
    shipping: "+ $4.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "thePullBoys",
    condition: "Lightly Played Holofoil",
    price: "$75.00",
    shipping: "+ $4.89 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The Doctier",
    condition: "Near Mint Holofoil",
    price: "$80.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SchmityTCG",
    condition: "Near Mint Holofoil",
    price: "$80.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Mint as Muk",
    condition: "Near Mint Holofoil",
    price: "$79.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The Wasteland Gaming",
    condition: "Near Mint Holofoil",
    price: "$82.24",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Sages Store",
    condition: "Near Mint Holofoil",
    price: "$82.48",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Galactic Kentwood",
    condition: "Lightly Played Holofoil",
    price: "$81.88",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Zulus Games",
    condition: "Near Mint Holofoil",
    price: "$85.12",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokeAntiquarian",
    condition: "Near Mint Holofoil",
    price: "$85.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Cynthias Garchomp",
    condition: "Near Mint Holofoil",
    price: "$86.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The Game Haven",
    condition: "Near Mint Holofoil",
    price: "$87.84",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Highlands City Gym",
    condition: "Near Mint Holofoil",
    price: "$87.17",
    shipping: "+ $1.79 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "EBgamesTCG",
    condition: "Lightly Played Holofoil",
    price: "$89.69",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Play to Win Games",
    condition: "Near Mint Holofoil",
    price: "$89.97",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Poke Samurai",
    condition: "Near Mint Holofoil",
    price: "$90.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "SevenOneSevenTCG",
    condition: "Near Mint Holofoil",
    price: "$89.99",
    shipping: "+ $3.49 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ThriceAsNice",
    condition: "Lightly Played Holofoil",
    price: "$98.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "LonelyTaquitoShopTCG",
    condition: "Near Mint Holofoil",
    price: "$99.95",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "CCGHouse",
    condition: "Near Mint Holofoil",
    price: "$99.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "PokePullsUltd",
    condition: "Near Mint Holofoil",
    price: "$99.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "pdcards",
    condition: "Lightly Played Holofoil",
    price: "$99.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Skulltulaman tcg",
    condition: "Near Mint Holofoil",
    price: "$100.00",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Green Panda Cards",
    condition: "Near Mint Holofoil",
    price: "$100.00",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GTGamesca",
    condition: "Near Mint Holofoil",
    price: "$98.15",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Xianyunan",
    condition: "Near Mint Holofoil",
    price: "$99.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Poke Twins",
    condition: "Near Mint Holofoil",
    price: "$104.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Full Moon Games",
    condition: "Moderately Played Holofoil",
    price: "$105.38",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Sharpe Games",
    condition: "Near Mint Holofoil",
    price: "$110.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "pdcards",
    condition: "Near Mint Holofoil",
    price: "$119.99",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Full Moon Games",
    condition: "Lightly Played Holofoil",
    price: "$118.54",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "The Hidden Emporium",
    condition: "Near Mint Holofoil",
    price: "$125.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Omega Portal CCG",
    condition: "Near Mint Holofoil",
    price: "$150.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Captain Sandwich",
    condition: "Near Mint Holofoil",
    price: "$150.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "MKTreasures",
    condition: "Near Mint Holofoil",
    price: "$149.94",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "TCG Worldwide Pro",
    condition: "Near Mint Holofoil",
    price: "$149.95",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Lunatics Vault",
    condition: "Near Mint Holofoil",
    price: "$150.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "GameShrinks",
    condition: "Near Mint Holofoil",
    price: "$155.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Full Moon Games",
    condition: "Near Mint Holofoil",
    price: "$164.65",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ygomtgca",
    condition: "Lightly Played Holofoil",
    price: "$179.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "JiBs Singles",
    condition: "Near Mint Holofoil",
    price: "$175.00",
    shipping: "+ $4.75 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "ShadowGamesTCG",
    condition: "Near Mint Holofoil",
    price: "$179.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "BoogieThreeSeven",
    condition: "Near Mint Holofoil",
    price: "$220.00",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Masta Packs",
    condition: "Near Mint Holofoil",
    price: "$550.00",
    pokemonValue: "pokemon-sv03-obsidian-flames-charizard-ex-223-197",
  },
  {
    seller: "Red Husky Games",
    condition: "Near Mint Holofoil",
    price: "$6.26",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "spftreasurefinds",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AT Hiker Yoshi",
    condition: "Near Mint Holofoil",
    price: "$5.20",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Articmage TCG",
    condition: "Near Mint Holofoil",
    price: "$5.50",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MangosTrading",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "KCM Collectibles LLC",
    condition: "Near Mint Holofoil",
    price: "$5.60",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Bluestar Poke Cards",
    condition: "Near Mint Holofoil",
    price: "$5.70",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Yashs Cards",
    condition: "Near Mint Holofoil",
    price: "$5.66",
    shipping: "+ $1.10 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Trainers Lounge",
    condition: "Near Mint Holofoil",
    price: "$5.91",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PremiumPokePacks",
    condition: "Near Mint Holofoil",
    price: "$5.91",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "QualityNode",
    condition: "Lightly Played Holofoil",
    price: "$5.59",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Raleigh Rockruffs",
    condition: "Near Mint Holofoil",
    price: "$5.66",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Borderless Gaming",
    condition: "Near Mint Holofoil",
    price: "$5.66",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeYinzerTCG",
    condition: "Near Mint Holofoil",
    price: "$5.75",
    shipping: "+ $1.22 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Black Rose Garden",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Yakurukes Shop",
    condition: "Near Mint Holofoil",
    price: "$5.67",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BnW Games",
    condition: "Near Mint Holofoil",
    price: "$5.67",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CardOroGaming",
    condition: "Near Mint Holofoil",
    price: "$6.99",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "ArcaneTCG",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Psyduck Depot",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MonsteraCardsHI",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "WorldChampionTrading",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Cmoss Collectibles",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JM PokeCardShop",
    condition: "Lightly Played Holofoil",
    price: "$5.50",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Express TCG",
    condition: "Near Mint Holofoil",
    price: "$7.08",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AW Collectibles",
    condition: "Near Mint Holofoil",
    price: "$5.91",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AR Collectibles LLC",
    condition: "Near Mint Holofoil",
    price: "$5.93",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Poke Deeg",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Crafty Crow",
    condition: "Near Mint Holofoil",
    price: "$5.98",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Stonedrink Collects",
    condition: "Near Mint Holofoil",
    price: "$7.25",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Chase Place",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DesertCollects",
    condition: "Near Mint Holofoil",
    price: "$5.78",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Sleepybears",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TomTomsTCG",
    condition: "Near Mint Holofoil",
    price: "$6.05",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Tgctcg",
    condition: "Near Mint Holofoil",
    price: "$6.07",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Slabhobby",
    condition: "Lightly Played Holofoil",
    price: "$7.39",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Kowalczyk Card shop",
    condition: "Near Mint Holofoil",
    price: "$6.23",
    shipping: "+ $1.18 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "ElzPokeStop",
    condition: "Lightly Played Holofoil",
    price: "$6.42",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "knitrcards",
    condition: "Near Mint Holofoil",
    price: "$6.11",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DeeBreacher",
    condition: "Near Mint Holofoil",
    price: "$6.28",
    shipping: "+ $1.19 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Kuper Cards",
    condition: "Near Mint Holofoil",
    price: "$6.18",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "StoreCamping",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PA Poke Mom",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Qualitypro Sales",
    condition: "Near Mint Holofoil",
    price: "$6.25",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "SquirtleUseBubble",
    condition: "Near Mint Holofoil",
    price: "$5.51",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TeamRocketsPlunders",
    condition: "Near Mint Holofoil",
    price: "$6.52",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Salamence Supply",
    condition: "Near Mint Holofoil",
    price: "$5.52",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CollectiBrews Cards",
    condition: "Near Mint Holofoil",
    price: "$6.29",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "GemTCG",
    condition: "Near Mint Holofoil",
    price: "$6.06",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "LuckyPandaTCG",
    condition: "Near Mint Holofoil",
    price: "$6.25",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeZales",
    condition: "Near Mint Holofoil",
    price: "$6.06",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Sharcozard LLC",
    condition: "Near Mint Holofoil",
    price: "$6.57",
    shipping: "+ $1.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MuleyFreak",
    condition: "Near Mint Holofoil",
    price: "$6.13",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "KGT Collectibles",
    condition: "Near Mint Holofoil",
    price: "$5.65",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "nathanieltm",
    condition: "Near Mint Holofoil",
    price: "$6.39",
    shipping: "+ $1.29 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Nearly Played TCG",
    condition: "Near Mint Holofoil",
    price: "$6.70",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Gamers Pair a Dice",
    condition: "Lightly Played Holofoil",
    price: "$7.69",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "StenTheSnake",
    condition: "Near Mint Holofoil",
    price: "$6.46",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Pikaluxe",
    condition: "Lightly Played Holofoil",
    price: "$5.99",
    shipping: "+ $1.75 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeBash TCG",
    condition: "Near Mint Holofoil",
    price: "$7.74",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Card Pirate LLC",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Alberick",
    condition: "Near Mint Holofoil",
    price: "$7.77",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CardEO Clinic",
    condition: "Lightly Played Holofoil",
    price: "$6.50",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "RookieandRare",
    condition: "Near Mint Holofoil",
    price: "$6.03",
    shipping: "+ $1.75 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Covenant Cards Shop",
    condition: "Near Mint Holofoil",
    price: "$6.49",
    shipping: "+ $1.30 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "YiedTcg",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $1.30 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "GastlyGrabs",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "oldsaltcollectables",
    condition: "Near Mint Holofoil",
    price: "$6.51",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "OptimisticPrime",
    condition: "Near Mint Holofoil",
    price: "$7.15",
    shipping: "+ $0.69 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "SellingTradingCards",
    condition: "Near Mint Holofoil",
    price: "$7.92",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Sheazus",
    condition: "Near Mint Holofoil",
    price: "$7.93",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "phantomich singles",
    condition: "Near Mint Holofoil",
    price: "$6.94",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BattlePhase",
    condition: "Near Mint Holofoil",
    price: "$7.95",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Rippin Packs TCG",
    condition: "Near Mint Holofoil",
    price: "$6.96",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BarrettoTCG",
    condition: "Near Mint Holofoil",
    price: "$6.66",
    shipping: "+ $1.30 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "ToTheMoon TCG",
    condition: "Near Mint Holofoil",
    price: "$6.99",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Gigis rare candy",
    condition: "Near Mint Holofoil",
    price: "$6.49",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Lucky Vault",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BSSCodes",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Card Rx",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $3.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BoncesCardMarket",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Retro Card Junkie",
    condition: "Near Mint Holofoil",
    price: "$8.00",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "NuatCollectibles",
    condition: "Near Mint Holofoil",
    price: "$6.04",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Granite State TCG",
    condition: "Near Mint Holofoil",
    price: "$6.75",
    shipping: "+ $1.29 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PognarTCG",
    condition: "Near Mint Holofoil",
    price: "$6.75",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JPPokeStory",
    condition: "Near Mint Holofoil",
    price: "$6.76",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Ls card corner",
    condition: "Near Mint Holofoil",
    price: "$6.73",
    shipping: "+ $1.35 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "FoiltasticAdventures",
    condition: "Near Mint Holofoil",
    price: "$4.00",
    shipping: "+ $4.09 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeCardfinder",
    condition: "Near Mint Holofoil",
    price: "$5.15",
    shipping: "+ $3.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Poke Casa",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    shipping: "+ $1.21 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Ark TCG",
    condition: "Near Mint Holofoil",
    price: "$8.24",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MasterTheSet",
    condition: "Near Mint Holofoil",
    price: "$7.25",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JMSneakers",
    condition: "Near Mint Holofoil",
    price: "$7.25",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Guilded Grayland",
    condition: "Near Mint Holofoil",
    price: "$7.26",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CollectorBee",
    condition: "Near Mint Holofoil",
    price: "$6.30",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Vibingwithriley",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeKantoOG",
    condition: "Near Mint Holofoil",
    price: "$6.31",
    shipping: "+ $2.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Pegasus Collectibles",
    condition: "Near Mint Holofoil",
    price: "$6.35",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Marias Collectibles",
    condition: "Near Mint Holofoil",
    price: "$7.39",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Charliezcollects",
    condition: "Near Mint Holofoil",
    price: "$6.21",
    shipping: "+ $2.20 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Hotbeef tcg",
    condition: "Near Mint Holofoil",
    price: "$7.18",
    shipping: "+ $1.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "WanderingAtelier",
    condition: "Near Mint Holofoil",
    price: "$6.97",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Kennies Shop",
    condition: "Near Mint Holofoil",
    price: "$8.49",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Birds Nest",
    condition: "Near Mint Holofoil",
    price: "$4.50",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Nerdy Vixen",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    shipping: "+ $1.50 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Command Zone GandH",
    condition: "Near Mint Holofoil",
    price: "$8.50",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Giraffe's Cards",
    condition: "Near Mint Holofoil",
    price: "$8.57",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MassCollect",
    condition: "Near Mint Holofoil",
    price: "$6.89",
    shipping: "+ $1.69 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeMern",
    condition: "Near Mint Holofoil",
    price: "$7.31",
    shipping: "+ $1.29 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Big man charizard",
    condition: "Near Mint Holofoil",
    price: "$6.62",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "GG Lehi",
    condition: "Near Mint Holofoil",
    price: "$6.67",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Twenty Lore TCG",
    condition: "Near Mint Holofoil",
    price: "$6.69",
    shipping: "+ $2.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Slabhobby",
    condition: "Near Mint Holofoil",
    price: "$8.72",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Averys Garden",
    condition: "Near Mint Holofoil",
    price: "$7.74",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Paper Tiger Co",
    condition: "Near Mint Holofoil",
    price: "$6.76",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Brickeria",
    condition: "Near Mint Holofoil",
    price: "$6.79",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "InfiniteTCGFW",
    condition: "Lightly Played Holofoil",
    price: "$7.35",
    shipping: "+ $1.49 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Alternate Dimensions",
    condition: "Lightly Played Holofoil",
    price: "$6.91",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Swamped Collectibles",
    condition: "Near Mint Holofoil",
    price: "$8.95",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "NSG Studio",
    condition: "Near Mint Holofoil",
    price: "$6.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "NSG Studio",
    condition: "Near Mint Holofoil",
    price: "$6.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Pokeparks cards",
    condition: "Near Mint Holofoil",
    price: "$4.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Dragonitexpress",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "StarMan Card Shop",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokePremier",
    condition: "Near Mint Holofoil",
    price: "$8.00",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Card Cache",
    condition: "Near Mint Holofoil",
    price: "$7.25",
    shipping: "+ $1.76 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Littleroot Games",
    condition: "Near Mint Holofoil",
    price: "$9.03",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JaggerCollectibles",
    condition: "Near Mint Holofoil",
    price: "$6.06",
    shipping: "+ $3.00 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "GamingUnderground",
    condition: "Near Mint Holofoil",
    price: "$9.15",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "ZarnainACG",
    condition: "Near Mint Holofoil",
    price: "$6.26",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Meeple Manor",
    condition: "Lightly Played Holofoil",
    price: "$7.99",
    shipping: "+ $1.27 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JDSxShop",
    condition: "Near Mint Holofoil",
    price: "$8.00",
    shipping: "+ $1.31 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Duckman Collectibles",
    condition: "Near Mint Holofoil",
    price: "$6.47",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DJsCardsandGames",
    condition: "Near Mint Holofoil",
    price: "$8.49",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Frozen Aspen Cards",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TPC Jax",
    condition: "Near Mint Holofoil",
    price: "$6.66",
    shipping: "+ $2.95 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Trainer Supply",
    condition: "Near Mint Holofoil",
    price: "$5.74",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TheCardGuyTCG",
    condition: "Near Mint Holofoil",
    price: "$7.75",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TrainersPokeStop",
    condition: "Near Mint Holofoil",
    price: "$5.78",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "ValleyCollectiblesVa",
    condition: "Near Mint Holofoil",
    price: "$8.33",
    shipping: "+ $1.59 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Powernett",
    condition: "Near Mint Holofoil",
    price: "$9.97",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MochiMintCo",
    condition: "Near Mint Holofoil",
    price: "$7.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "EliteFourMaster",
    condition: "Near Mint Holofoil",
    price: "$7.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Luckoftheirish cards",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DoubleDollar Cards",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "YGOkidMase",
    condition: "Near Mint Holofoil",
    price: "$9.99",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Mysterious Inventory",
    condition: "Near Mint Holofoil",
    price: "$9.99",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Memory Merchants",
    condition: "Near Mint Holofoil",
    price: "$5.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AndrickGames",
    condition: "Near Mint Holofoil",
    price: "$8.00",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Doctier",
    condition: "Near Mint Holofoil",
    price: "$10.00",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Metal N Ink",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.25 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Benjis Booster Pack",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.29 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Tegridy Games",
    condition: "Near Mint Holofoil",
    price: "$5.39",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "EmberSkies",
    condition: "Near Mint Holofoil",
    price: "$5.40",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DadSpartacus Cards",
    condition: "Near Mint Holofoil",
    price: "$5.46",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Comic Book Store",
    condition: "Near Mint Holofoil",
    price: "$5.46",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "JKCollects",
    condition: "Near Mint Holofoil",
    price: "$5.50",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MacKards",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.51 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BadHabits TCG",
    condition: "Near Mint Holofoil",
    price: "$6.09",
    shipping: "+ $4.49 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Poke Bazzar",
    condition: "Near Mint Holofoil",
    price: "$5.62",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Sports Nuts TCG",
    condition: "Near Mint Holofoil",
    price: "$5.63",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Game Cafe",
    condition: "Near Mint Holofoil",
    price: "$5.93",
    shipping: "+ $4.75 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "G2K JOHNSON CITY",
    condition: "Lightly Played Holofoil",
    price: "$5.69",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "G2K GAMES NORTON",
    condition: "Lightly Played Holofoil",
    price: "$5.69",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "StrongsCardShop",
    condition: "Near Mint Holofoil",
    price: "$5.79",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BrappaMart",
    condition: "Near Mint Holofoil",
    price: "$5.82",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Ketzal collectibles",
    condition: "Near Mint Holofoil",
    price: "$5.89",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "SupaFatManCollects",
    condition: "Near Mint Holofoil",
    price: "$5.91",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Rip and Ships",
    condition: "Near Mint Holofoil",
    price: "$5.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Jonny T's Corner",
    condition: "Lightly Played Holofoil",
    price: "$8.99",
    shipping: "+ $1.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Sageandgrookey",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "DreadBreaks",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CodyLs Shop",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Pokey collects",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Spookems TCG",
    condition: "Near Mint Holofoil",
    price: "$6.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Bakers tcg",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Miles Hobby Shop",
    condition: "Near Mint Holofoil",
    price: "$11.00",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Celestial Cave",
    condition: "Near Mint Holofoil",
    price: "$8.01",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Grizzly Bear Tech",
    condition: "Near Mint Holofoil",
    price: "$7.09",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Skrtcurts",
    condition: "Near Mint Holofoil",
    price: "$6.10",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AgentNerd TCG Shop",
    condition: "Near Mint Holofoil",
    price: "$6.16",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Quest Realm",
    condition: "Lightly Played Holofoil",
    price: "$8.24",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Keeksz Cards",
    condition: "Near Mint Holofoil",
    price: "$7.25",
    shipping: "+ $3.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Other Side",
    condition: "Near Mint Holofoil",
    price: "$6.28",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Trading Card World",
    condition: "Near Mint Holofoil",
    price: "$6.35",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Black Swamp Games",
    condition: "Near Mint Holofoil",
    price: "$6.37",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Super Heroes",
    condition: "Lightly Played Holofoil",
    price: "$6.42",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Dead Card Collective",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "PokeStopMotion",
    condition: "Near Mint Holofoil",
    price: "$6.50",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MachokinGains",
    condition: "Near Mint Holofoil",
    price: "$6.74",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Kingpyn TCG",
    condition: "Near Mint Holofoil",
    price: "$6.97",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Wasteland Gaming",
    condition: "Near Mint Holofoil",
    price: "$10.99",
    shipping: "+ $0.98 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "CollectiCards",
    condition: "Near Mint Holofoil",
    price: "$7.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Game And Company",
    condition: "Near Mint Holofoil",
    price: "$9.10",
    shipping: "+ $2.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "RoseNRips",
    condition: "Near Mint Holofoil",
    price: "$7.30",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Nikkiakkiz",
    condition: "Near Mint Holofoil",
    price: "$7.41",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Just Toying Around",
    condition: "Near Mint Holofoil",
    price: "$7.50",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Just Toying Around",
    condition: "Near Mint Holofoil",
    price: "$7.50",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "The Game Haven",
    condition: "Near Mint Holofoil",
    price: "$11.59",
    shipping: "+ $0.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "AlphaStrikeGames LLC",
    condition: "Near Mint Holofoil",
    price: "$8.05",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Play Unplugged",
    condition: "Near Mint Holofoil",
    price: "$8.27",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "BlackSunGamesMDII",
    condition: "Near Mint Holofoil",
    price: "$13.72",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Vincerovar",
    condition: "Near Mint Holofoil",
    price: "$9.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Lebnani TCG",
    condition: "Near Mint Holofoil",
    price: "$9.99",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "MD Sports Cards",
    condition: "Near Mint Holofoil",
    price: "$10.98",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Whatsnext",
    condition: "Near Mint Holofoil",
    price: "$12.00",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Con Heo",
    condition: "Near Mint Holofoil",
    price: "$15.00",
    shipping: "+ $2.13 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "Full Moon Games",
    condition: "Near Mint Holofoil",
    price: "$14.25",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
  {
    seller: "TCG Worldwide Pro",
    condition: "Near Mint Holofoil",
    price: "$19.95",
    shipping: "+ $4.99 Shipping",
    pokemonValue: "pokemon-sv08-surging-sparks-latias-ex-076-191",
  },
];
